<?php

return [
    // Getting started
    'Add a profile picture' => 'تصویر پروفایل اضافه کن',
    'Write your first post' => 'اولین پستت را بنویس',
    'Like a post you enjoyed' => 'به پستی که دوست داشتی لایک بده',
    'Check in for the first time' => 'برای اولین بار حضور روزانه را ثبت کن',
    'Getting started' => 'شروع کار',

    // Points rules
    'Check-in' => 'حضور روزانه',
    'Daily check-in' => 'حضور روزانه',
    'Streak bonus, per day in a row' => 'پاداش رشته‌ی روزانه، به ازای هر روز پیوسته',
    '7-day streak bonus' => 'پاداش ۷ روز پیوسته',
    '30-day streak bonus' => 'پاداش ۳۰ روز پیوسته',

    // Check-in
    'Day %d of the streak' => 'روز %d از رشته‌ی روزانه',
    '%d days in a row' => '%d روز پیوسته',

    // Levels
    '%s of %s to Lv %d' => '%s از %s تا سطح %d',
    'Top level' => 'بالاترین سطح',
    'Level %d' => 'سطح %d',
    'Level' => 'سطح',
    'Check-ins' => 'حضورهای روزانه',
    '%d in a row' => '%d روز پیوسته',
    '#%d' => '#%d',
    
// Leaderboard boards
'Points' => 'امتیاز',
'Check-ins' => 'حضور روز',
'Streaks' => 'حضور ممتد',
'Topics' => 'موضوع‌ها',

// Streak descriptions
'The longest runs going on now.' => 'طولانی‌ترین رشته‌های فعلی.',
'%d-day streak' => 'رشته‌ی %d روزه',
'%d days in total' => 'در مجموع %d روز',

    // Member menu and cards
    'Checked in today' => 'امروز حضور ثبت شد',
    'Check in' => 'ثبت حضور',
    'Growth' => 'رشد',
    'Leaderboard' => 'امتیاز کاربران',
    '%d days in a row · see you tomorrow' => '%d روز پیوسته · فردا می‌بینیمت',
    'See you tomorrow' => 'فردا می‌بینیمت',
    'Keep your %d-day streak going' => 'رشته‌ی %d روزه‌ات را ادامه بده',
    'Start a streak today' => 'امروز رشته‌ی روزانه را شروع کن',
    'M T W T F S S' => 'د س چ پ ج ش ی',

    // Points page
    '+%d today' => '+%d امروز',
    'All ways to earn' => 'همه‌ی راه‌های کسب امتیاز',
    'Your progress today' => 'پیشرفت امروز تو',

    // Old task names
    'Set an avatar' => 'تنظیم آواتار',
    'Fill in your profile' => 'تکمیل پروفایل',
    'Start your first topic' => 'شروع اولین موضوع',
    'Write your first reply' => 'نوشتن اولین پاسخ',
    'Like a post' => 'لایک کردن یک پست',
    'Reply to a topic' => 'پاسخ دادن به یک موضوع',
    'Like three posts' => 'لایک کردن سه پست',
    'Start a topic' => 'شروع یک موضوع',
    'Three topics this week' => 'سه موضوع در این هفته',
    'Ten replies this week' => 'ده پاسخ در این هفته',
    'Receive ten likes this week' => 'دریافت ده لایک در این هفته',
    'Invite a friend' => 'دعوت یک دوست',
    'Task: %s' => 'کار: %s',
    'Made up a missed check-in' => 'جبران یک حضور روزانه از دست‌رفته',

    // Admin settings
    'Levels' => 'سطح‌ها',
    'Earn levels from posts and topics instead of points' => 'کسب سطح از پست‌ها و موضوع‌ها به‌جای امتیاز',
    'The streak bonus stops growing after (days)' => 'پاداش رشته‌ی روزانه بعد از این تعداد روز دیگر افزایش نمی‌یابد',
    'The amounts are under Admin → Points (Check-in and Getting started).' => 'مقادیر در بخش مدیریت ← امتیازها قرار دارند (حضور روزانه و شروع کار).',
    'Show the level (Lv3) after the name on posts' => 'نمایش سطح (مثلاً Lv3) بعد از نام کاربر در پست‌ها',
    'Sidebar card' => 'کارت کنار صفحه',
    'On the topic lists' => 'در فهرست موضوع‌ها',
    'On every page' => 'در همه‌ی صفحه‌ها',
    'Off' => 'خاموش',
    'Members per leaderboard' => 'تعداد اعضا در هر جدول امتیاز',
    'Leaderboard card in the right column' => 'کارت جدول امتیازها در ستون راست',
    'Members per board on the Leaderboard card' => 'تعداد اعضا در هر جدول روی کارت جدول امتیازها',
    'Boards on the Leaderboard card, in order' => 'جدول‌های روی کارت جدول امتیازها، به ترتیب',
    'Comma separated: points, checkins, streaks, topics (and boards other plugins add). Empty: all of them. The card refreshes every five minutes.' => 'با کاما جدا کنید: points، checkins، streaks، topics و جدول‌هایی که افزونه‌های دیگر اضافه می‌کنند. خالی بگذارید: همه نمایش داده می‌شوند. این کارت هر پنج دقیقه به‌روزرسانی می‌شود.',

    // Growth pages
    'Overview' => 'نمای کلی',
    'Progress' => 'پیشرفت',
    'Ways to earn' => 'راه‌های کسب امتیاز',
    'Top members' => 'اعضای برتر',
    'View all' => 'مشاهده همه',
    'Nobody is on this board yet.' => 'هنوز کسی در این جدول نیست.',
    'Check in every day, earn points, climb the levels' => 'هر روز حضور ثبت کن، امتیاز بگیر، سطح کسب کن',
    'Members check in once a day, keep a streak and climb the levels.' => 'اعضا روزی یک‌بار حضور ثبت می‌کنند، رشته‌ی روزانه می‌سازند و سطح کسب می‌کنند.',
    'Sign in to check in' => 'برای ثبت حضور وارد شوید',
    'points a day' => 'امتیاز در روز',
    'days in a row' => 'روز پیوسته',
    'Rank' => 'رتبه',
    'Best streak' => 'بهترین رشته',
    '%d days' => '%d روز',
    'Earn today' => 'امروز کسب کن',
    'All progress' => 'همه‌ی پیشرفت',
    'Nothing pays points yet.' => 'هنوز چیزی امتیاز نمی‌دهد.',
    'up to %d times a day' => 'تا %d بار در روز',
    'Checked in today · see you tomorrow' => 'امروز حضور ثبت شد · فردا می‌بینیمت',
    'Checked in: +%1$d points, day %2$d in a row.' => 'حضور ثبت شد: +%1$d امتیاز، روز %2$d پیوسته.',
    'Checked in. Day %d in a row.' => 'حضور ثبت شد. روز %d پیوسته.',
    'You have already checked in today.' => 'شما امروز قبلاً حضور ثبت کرده‌اید.',
    '+%d each' => '+%d هر بار',
    'Done' => 'انجام شد',
    '+%d when all are done' => '+%d وقتی همه انجام شوند',
    'Getting started: all %1$d steps done, +%2$d earned' => 'شروع کار: همه‌ی %1$d مرحله انجام شد، +%2$d کسب شد',
    'Also pays, without a daily limit' => 'همچنین امتیاز می‌دهد، بدون محدودیت روزانه',
    'The staff set the amounts; the daily limits start again at midnight.' => 'مقادیر توسط تیم تنظیم شده؛ محدودیت‌های روزانه هر شب از نو شروع می‌شوند.',
    'My points' => 'امتیازهای من',
    'Sign in to see your level and what you can still earn today.' => 'برای دیدن سطح و آنچه امروز می‌توانی کسب کنی وارد شوید.',
    'Sign in' => 'ورود',
    '%s posts' => '%s پست',
    '%s points' => '%s امتیاز',
    '%1$s of %2$s · %3$s more to Lv %4$d %5$s' => '%1$s از %2$s · %3$s تا سطح %4$d %5$s باقی مانده',
    '%s to go' => '%s باقی مانده',
    'Posts and topics needed for each level.' => 'پست‌ها و موضوع‌های مورد نیاز برای هر سطح.',
    'Points needed for each level.' => 'امتیازهای مورد نیاز برای هر سطح.',
    'You are here' => 'شما اینجا هستید',
    'Previous month' => 'ماه قبل',
    'Next month' => 'ماه بعد',
    'Checked in' => 'حضور ثبت شد',
    '%d days in total' => 'در مجموع %d روز',
    'Best streak %d' => 'بهترین رشته %d',
    'Nobody has checked in yet today. Be the first.' => 'هنوز امروز کسی حضور ثبت نکرده. اولین باش!',
    'Ranked by points balance.' => 'رتبه‌بندی بر اساس مجموع امتیازها.',
    '%s points' => '%s امتیاز',
    '%s point' => '%s امتیاز',
    'Ranked by days checked in.' => 'رتبه‌بندی بر اساس روزهای حضور.',
    '%s days' => '%s روز',
    '%s day' => '%s روز',
    'The longest runs going on now.' => 'طولانی‌ترین رشته‌های فعلی.',
    'Ranked by topics started.' => 'رتبه‌بندی بر اساس موضوع‌های شروع‌شده.',
    '%s topics' => '%s موضوع',
    '%s topic' => '%s موضوع',
    'Your rank: #%d' => 'رتبه‌ی تو: #%d',
    'You' => 'تو',
    'Level deleted.' => 'سطح حذف شد.',
    'The level needs a name.' => 'سطح نیاز به نام دارد.',
    'Level saved.' => 'سطح ذخیره شد.',
    'A member reaches a level when their %s reach its threshold. The amounts members earn are under Admin → Points.' => 'یک عضو وقتی به سطح می‌رسد که %s او به آستانه برسد. مقادیر کسب اعضا در مدیریت ← امتیازها است.',
    'Add level' => 'افزودن سطح',
    'No levels yet.' => 'هنوز سطحی نیست.',
    'Level number' => 'شماره سطح',
    'Threshold' => 'آستانه',
    'Reached at this many %s.' => 'در این تعداد %s می‌رسد.',
    'Name' => 'نام',
    'Save' => 'ذخیره',
    'New level' => 'سطح جدید',
    'Delete level "%s"?' => 'سطح «%s» حذف شود؟',
    'Delete' => 'حذف',
    'Edit' => 'ویرایش',
];