<?php

return [
    // Poll plugin
    'Poll' => 'نظرسنجی',
    'Polls' => 'نظرسنجی‌ها',
    'A poll on a topic: the writer adds the options in the composer, members vote under the first post and watch the bars fill. Single or multiple choice, secret or open ballot, an optional closing date.' => 'نظرسنجی در موضوع: نویسنده گزینه‌ها را هنگام ساخت موضوع اضافه می‌کند، اعضا زیر اولین نوشته رأی می‌دهند و نتیجه را به‌صورت نوار مشاهده می‌کنند. انتخاب تکی یا چندگانه، رأی‌گیری خصوصی یا عمومی و تاریخ پایان اختیاری.',
    'Who may add a poll' => 'چه کسی می‌تواند نظرسنجی اضافه کند',
    'Every member' => 'همه اعضا',
    'Moderators only' => 'فقط ناظران',
    'Options per poll' => 'تعداد گزینه‌ها در هر نظرسنجی',
    'Suggested closing time (days)' => 'زمان پیشنهادی پایان (روز)',
    '0 = polls stay open until the writer closes them.' => '۰ = نظرسنجی تا زمان بستن توسط نویسنده باز می‌ماند.',
    'Signed-out visitors see the results' => 'بازدیدکنندگان خارج‌شده از حساب نتایج را ببینند',
    'Show a Poll mark in topic lists' => 'نمایش نشان نظرسنجی در فهرست موضوع‌ها',
    'pick up to %d' => 'انتخاب حداکثر %d گزینه',
    'open ballot' => 'رأی‌گیری عمومی',
    'closed' => 'بسته‌شده',
    '%s voted' => '%s نفر رأی داده‌اند',
    '%s votes' => '%s رأی',
    'Results are shown once you vote.' => 'نتایج پس از رأی‌دادن نمایش داده می‌شوند.',
    'Vote' => 'رأی دادن',
    'You can change your vote.' => 'می‌توانید رأی خود را تغییر دهید.',
    'Sign in to vote' => 'برای رأی‌دادن وارد شوید',
    'Closed' => 'بسته‌شده',
    'No closing date' => 'بدون تاریخ پایان',
    'Closes in %s' => 'تا بسته‌شدن: %s',
    'under a minute' => 'کمتر از یک دقیقه',
    '%d days' => '%d روز',
    '%d hours' => '%d ساعت',
    '%d minutes' => '%d دقیقه',
    'Withdraw my vote' => 'پس‌گرفتن رأی من',
    'Reopen the poll' => 'بازکردن دوباره نظرسنجی',
    'Close the poll' => 'بستن نظرسنجی',
    'Delete the poll' => 'حذف نظرسنجی',
    'Delete this poll and every vote in it?' => 'این نظرسنجی و همه رأی‌های آن حذف شود؟',
    'This topic has a poll' => 'این موضوع یک نظرسنجی دارد',
    '%s already voted, so the questions and options cannot be changed. Close or delete the poll from the topic page.' => '%s نفر قبلاً رأی داده‌اند؛ بنابراین پرسش و گزینه‌ها قابل تغییر نیستند. نظرسنجی را از صفحه موضوع ببندید یا حذف کنید.',
    'Question' => 'پرسش',
    'Left empty, the topic title is the question' => 'اگر خالی بماند، عنوان موضوع به‌عنوان پرسش استفاده می‌شود',
    'Options' => 'گزینه‌ها',
    'One option per line' => 'هر گزینه در یک خط',
    'Between 2 and %d lines. Leave empty for no poll.' => 'بین ۲ تا %d خط. برای نساختن نظرسنجی خالی بگذارید.',
    'Choices per voter' => 'تعداد انتخاب برای هر رأی‌دهنده',
    '1 = pick one option.' => '۱ = انتخاب یک گزینه.',
    'Close after (days)' => 'بستن پس از چند روز',
    '0 = the poll stays open.' => '۰ = نظرسنجی باز می‌ماند.',
    'Open ballot: everyone sees who voted for what' => 'رأی‌گیری عمومی: همه می‌بینند چه کسی به چه گزینه‌ای رأی داده است',
    'Voters may change their vote' => 'رأی‌دهندگان می‌توانند رأی خود را تغییر دهند',
    'Show the results before voting' => 'نمایش نتایج پیش از رأی‌دادن',
];